name: trend_browser
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  flutter_file_downloader: ^2.1.0
  flutter_inappwebview: ^6.1.5
  flutter_lints: ^5.0.0
  flutter_svg: ^2.1.0
  fluttertoast: ^8.2.12
  get: ^4.7.2
  get_storage: ^2.1.1
  mimecon: ^1.0.1
  shimmer: ^3.0.0
  http: ^1.3.0
  path: ^1.9.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  dio: ^5.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/img/